### PR TITLE
Refactor services, fixes #34

### LINKED ISSUE #34: Refactor song/room logic, proper service usage
Gijs en Jan-Willem

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
PR on PR

### CODE REVIEW

**Comment by GijsWeterings** [comment]
LGTM, we need to look at the tests soon tho

**Comment by JeremybellEU** [comment]
Agreed with Gijs =]

**Comment by Azkle** [comment]
LGTM

**Comment by JWGmeligMeyling** [comment]
Oops duplicate history due wrong rebase. Maybe reset to badd55a and then rebase on master after the merge of #37

**Comment by JWGmeligMeyling** [comment]
Rebased on master.

**Pull request closed without merging**
