### PR TITLE
Fixed centering of header timestamp

### PR DESCRIPTION
**Pull request by Azkle**
Made by Tim.

### CODE REVIEW

**Comment by Azkle** [comment]
LGTM

**Comment by JWGmeligMeyling** [comment]
Wouldnt this http://stackoverflow.com/a/18778769/2104280 be a cleaner approach rather than enforcing a forced width?

**Comment by JWGmeligMeyling** [comment]
btw if it works, might as well just merge it imo

**Comment by JeremybellEU** [comment]
Yeh let's just merge, it works ;p

**Pull request merged**
