### PR TITLE
Get rid of the spam. Can be found in the network tab.

### PR DESCRIPTION
**Pull request by JeremybellEU**

### CODE REVIEW

**Comment by Azkle** [comment]
LGTM, trivial

**Comment by JWGmeligMeyling** [comment]
Can't do it, the absence of this familiar log statement would break my heart :broken_heart:

**Comment by JWGmeligMeyling** [comment]
How cold you

**Comment by JWGmeligMeyling** [comment]
TBH It would be better to keep the log statements, but turn the debug related logs off in production:
```
module.config(function($logProvider){
  $logProvider.debugEnabled(false);
});
```

**Comment by JeremybellEU** [comment]
Yes, let's make a seperate issue for that.

**Pull request merged**
